name: Cache

on:
  pull_request:
    branches:
      - main

jobs: 
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2  # Faz checkout do código no repositório

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install  # Instala as dependências necessárias

      - name: Build the project
        run: npm run build  # Executa o build da aplicação Next.js

      - name: Send Discord Alert on Commit
        run: |
          curl -H "Content-Type: application/json" \
                -d '{
                      "content": "🚀 Novo Commit no Repositório\n\n**Branch**: '${{ github.ref }}'\n**Commit**: '${{ github.sha }}'\n**Autor**: '${{ github.actor }}'\n**Link do Commit**: https://github.com/${{ github.repository }}/commit/${{ github.sha }}"
                    }' \
                ${{ secrets.DISCORD_WEBHOOK_URL }}